DROP TABLE IF EXISTS Users, Items, Booking, Comments, Requestor CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email varchar(512) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Requestor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(2000) NOT NULL,
    requestor_id BIGINT,
    created timestamp,
    CONSTRAINT fk_requestor_to_users FOREIGN KEY(requestor_id) REFERENCES users(id),
    UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS Items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_item VARCHAR(255) NOT NULL,
    description_item VARCHAR(2000) NOT NULL,
    available_item BOOLEAN NOT NULL,
    user_id BIGINT,
    request_id BIGINT,
    CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_items_to_request FOREIGN KEY(request_id) REFERENCES requestor(id),
    UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS Booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_booking timestamp,
    end_booking timestamp,
    item_id BIGINT,
    booker_id BIGINT,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_booking_to_items FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_booking_to_users FOREIGN KEY(booker_id) REFERENCES users(id),
    UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS Comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    item_id BIGINT,
    author VARCHAR(255) NOT NULL,
    created timestamp,
    CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id),
    UNIQUE(id)
);

